export type Product = {
  name: string;
  icon: string;
  slug: string;
  offers: { label: string; priceRub: number }[];
};

export const products: Product[] = [
  {
    name: "Steam",
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Steam_icon_logo.svg/960px-Steam_icon_logo.svg.png",
    slug: "steam",
    offers: [
      { label: "1$", priceRub: 20 },
      { label: "5$", priceRub: 100 },
      { label: "10$", priceRub: 200 },
      { label: "20$", priceRub: 400 },
      { label: "50$", priceRub: 925 },
      { label: "100$", priceRub: 1850 },
    ],
  },
  {
    name: "Telegram Premium",
    icon: "https://smmlaboratory.com/image/data/3/telegrammpremium.svg",
    slug: "telegram-premium",
    offers: [
      { label: "1 месяц (со входом)", priceRub: 75 },
      { label: "1 месяц (без входа)", priceRub: 115 },
      { label: "3 месяца (без входа)", priceRub: 220 },
      { label: "6 месяцев (без входа)", priceRub: 320 },
      { label: "12 месяцев (без входа)", priceRub: 510 },
    ],
  },
  {
    name: "World of Tanks",
    icon: "https://www.google.com/s2/favicons?sz=128&domain_url=https://worldoftanks.eu",
    slug: "world-of-tanks",
    offers: [
      { label: "1000 золота", priceRub: 55 },
      { label: "3000 золота", priceRub: 160 },
      { label: "5000 золота", priceRub: 265 },
      { label: "12500 золота", priceRub: 665 },
      { label: "Подписка", priceRub: 125 },
    ],
  },
  {
    name: "ChatGPT Plus",
    icon: "https://www.google.com/s2/favicons?sz=128&domain_url=https://chatgpt.com",
    slug: "chatgpt-plus",
    offers: [{ label: "1 месяц", priceRub: 55 }],
  },
  {
    name: "Brawl Stars",
    icon: "https://static.vecteezy.com/system/resources/thumbnails/027/127/558/small_2x/brawl-stars-logo-brawl-stars-icon-transparent-free-png.png",
    slug: "brawl-stars",
    offers: [
      { label: "Brawl Pass", priceRub: 195 },
      { label: "Brawl Pass Plus", priceRub: 285 },
      { label: "Pro Pass", priceRub: 545 },
      { label: "30 гемов", priceRub: 45 },
      { label: "80 гемов", priceRub: 105 },
      { label: "170 гемов", priceRub: 185 },
    ],
  },
  {
    name: "Roblox",
    icon: "https://media.tenor.com/HO1YAH0_iMcAAAAj/roblox-logo.gif",
    slug: "roblox",
    offers: [
      { label: "40 Robux", priceRub: 20 },
      { label: "80 Robux", priceRub: 40 },
      { label: "120 Robux", priceRub: 50 },
      { label: "200 Robux", priceRub: 80 },
      { label: "400 Robux", priceRub: 125 },
      { label: "800 Robux", priceRub: 210 },
      { label: "1200 Robux", priceRub: 295 },
      { label: "1700 Robux", priceRub: 410 },
      { label: "4500 Robux", priceRub: 1055 },
      { label: "Roblox Premium 1 месяц + 1000 Robux", priceRub: 245 },
    ],
  },
  {
    name: "Standoff 2",
    icon: "https://standof.ru/wp-content/uploads/2023/07/favicon.png",
    slug: "standoff-2",
    offers: [
      { label: "100 голды", priceRub: 35 },
      { label: "500 голды", priceRub: 120 },
      { label: "1000 голды", priceRub: 215 },
      { label: "1500 голды", priceRub: 320 },
      { label: "2000 голды", priceRub: 355 },
      { label: "3000 голды", priceRub: 455 },
    ],
  },
  {
    name: "TikTok Coins",
    icon: "https://cdn-icons-png.freepik.com/256/3621/3621450.png?semt=ais_white_label",
    slug: "tiktok-coins",
    offers: [
      { label: "30 coins", priceRub: 20 },
      { label: "100 coins", priceRub: 50 },
      { label: "200 coins", priceRub: 85 },
      { label: "300 coins", priceRub: 105 },
    ],
  },
  {
    name: "YouTube Premium",
    icon: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Youtube_logo.png",
    slug: "youtube-premium",
    offers: [{ label: "1 месяц", priceRub: 75 }],
  },
  {
    name: "Spotify Premium",
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/3840px-Spotify_logo_without_text.svg.png",
    slug: "spotify-premium",
    offers: [
      { label: "1 месяц", priceRub: 65 },
      { label: "3 месяца", priceRub: 180 },
      { label: "6 месяцев", priceRub: 295 },
      { label: "12 месяцев", priceRub: 475 },
    ],
  },
  {
    name: "PUBG Mobile",
    icon: "https://pnghdpro.com/wp-content/themes/pnghdpro/download/social-media-and-brands/pubg-mobile-logo.png",
    slug: "pubg-mobile",
    offers: [
      { label: "60 UC", priceRub: 30 },
      { label: "325 UC", priceRub: 100 },
      { label: "660 UC", priceRub: 190 },
      { label: "720 UC", priceRub: 220 },
      { label: "1320 UC", priceRub: 365 },
      { label: "1800 UC", priceRub: 470 },
      { label: "Premium 1 месяц", priceRub: 35 },
      { label: "Premium 3 месяца", priceRub: 75 },
      { label: "Premium+ 1 месяц", priceRub: 235 },
      { label: "Premium+ 3 месяца", priceRub: 615 },
      { label: "Elite Pass", priceRub: 115 },
      { label: "Elite Pass Plus", priceRub: 225 },
      { label: "Elite Pass Max", priceRub: 535 },
    ],
  },
  {
    name: "Discord Nitro",
    icon: "https://www.google.com/s2/favicons?sz=128&domain_url=https://discord.com",
    slug: "discord-nitro",
    offers: [
      { label: "Nitro Basic 1 месяц", priceRub: 85 },
      { label: "Nitro Full 1 месяц", priceRub: 145 },
    ],
  },
  {
    name: "Mobile Legends",
    icon: "https://www.freepnglogos.com/uploads/logo-mobile-legend-png/logo-mobile-legend-nasce-team-psg-rrq-paris-saint-germain-sbarca-20.png",
    slug: "mobile-legends",
    offers: [
      { label: "50 + 50 алмазов", priceRub: 25 },
      { label: "150 + 150 алмазов", priceRub: 70 },
      { label: "250 + 250 алмазов", priceRub: 95 },
      { label: "500 + 500 алмазов", priceRub: 180 },
      { label: "Алмазный пропуск 7 дней", priceRub: 55 },
      { label: "Элитный пропуск 7 дней", priceRub: 30 },
      { label: "Эпический пропуск 30 дней", priceRub: 115 },
    ],
  },
  {
    name: "Clash of Clans",
    icon: "https://www.google.com/s2/favicons?sz=128&domain_url=https://supercell.com",
    slug: "clash-of-clans",
    offers: [
      { label: "80 гемов", priceRub: 35 },
      { label: "160 гемов", priceRub: 55 },
      { label: "240 гемов", priceRub: 75 },
      { label: "Оформление", priceRub: 195 },
    ],
  },
  {
    name: "Clash Royale",
    icon: "https://www.pngplay.com/wp-content/uploads/10/Clash-Royale-Logo-PNG-HD-Photos.png",
    slug: "clash-royale",
    offers: [
      { label: "Pass Royale", priceRub: 225 },
      { label: "80 гемов", priceRub: 25 },
      { label: "500 гемов", priceRub: 105 },
      { label: "1200 гемов", priceRub: 185 },
    ],
  },
  {
    name: "Free Fire",
    icon: "https://images.seeklogo.com/logo-png/50/2/free-fire-logo-png_seeklogo-500424.png",
    slug: "free-fire",
    offers: [
      { label: "110 алмазов", priceRub: 20 },
      { label: "341 алмаз", priceRub: 65 },
      { label: "520 алмазов", priceRub: 95 },
      { label: "1160 алмазов", priceRub: 185 },
      { label: "2398 алмазов", priceRub: 355 },
      { label: "6160 алмазов", priceRub: 865 },
    ],
  },
  {
    name: "GTA 5 RP / Majestic RP",
    icon: "https://gta5rp.com/_next/image?url=%2Fimages%2Flogo%2Fmain.png&w=1920&q=100",
    slug: "gta-5-rp-majestic-rp",
    offers: [
      { label: "10000$", priceRub: 30 },
      { label: "100 DP", priceRub: 30 },
      { label: "20000$", priceRub: 30 },
      { label: "100 MC", priceRub: 30 },
    ],
  },
  {
    name: "Radmir RP",
    icon: "https://www.google.com/s2/favicons?sz=128&domain_url=https://radmir.online",
    slug: "radmir-rp",
    offers: [{ label: "100 донат валюты", priceRub: 30 }],
  },
  {
    name: "Amazing RP",
    icon: "https://www.google.com/s2/favicons?sz=128&domain_url=https://amazing-rp.ru",
    slug: "amazing-rp",
    offers: [{ label: "100 донат валюты", priceRub: 30 }],
  },
  {
    name: "Black Russia",
    icon: "https://cdn140.picsart.com/327485001024211.png",
    slug: "black-russia",
    offers: [{ label: "100 донат валюты", priceRub: 30 }],
  },
  {
    name: "Telegram аккаунты",
    icon: "https://static.vecteezy.com/system/resources/previews/023/986/562/non_2x/telegram-logo-telegram-logo-transparent-telegram-icon-transparent-free-free-png.png",
    slug: "telegram-accounts",
    offers: [
      { label: "Молдова", priceRub: 50 },
      { label: "Украина", priceRub: 55 },
      { label: "Беларусь", priceRub: 55 },
      { label: "США", priceRub: 35 },
      { label: "Вьетнам", priceRub: 30 },
      { label: "Мьянма", priceRub: 30 },
      { label: "Индия", priceRub: 30 },
      { label: "Камерун", priceRub: 30 },
      { label: "Непал", priceRub: 30 },
      { label: "Йемен", priceRub: 30 },
      { label: "Сомали", priceRub: 30 },
      { label: "Эфиопия", priceRub: 30 },
      { label: "Сенегал", priceRub: 30 },
      { label: "Нигерия", priceRub: 30 },
      { label: "Индонезия", priceRub: 30 },
      { label: "Колумбия", priceRub: 30 },
      { label: "Бангладеш", priceRub: 30 },
      { label: "Великобритания", priceRub: 30 },
    ],
  },
  {
    name: "Telegram Stars",
    icon: "https://lztcdn.com/files/6514f1e6-dab4-4d49-806a-3ff22d7793e5.webp",
    slug: "telegram-stars",
    offers: [],
  },
  {
    name: "Epic Games пополнение",
    icon: "https://cms-assets.unrealengine.com/AjTAN1C8SLWRn7fg4wnzlz/cmd6p7ipv3hl707ohjnyhwki2",
    slug: "epic-games-topup",
    offers: [],
  },
  {
    name: "Minecraft",
    icon: "https://images.icon-icons.com/2699/PNG/512/minecraft_logo_icon_168974.png",
    slug: "minecraft",
    offers: [],
  },
  {
    name: "PlayStation",
    icon: "https://www.pngkey.com/png/full/7-74293_la-siguiente-playstation-playstation-4-logo-png.png",
    slug: "playstation",
    offers: [],
  },
  {
    name: "Boosty",
    icon: "https://images.live.vkvideo.ru/image/31715c5a-91c0-455b-994f-31650954caee?change_time=1729181151&mw=640",
    slug: "boosty",
    offers: [],
  },
  {
    name: "Twitch",
    icon: "https://cdn-icons-png.flaticon.com/512/3938/3938117.png",
    slug: "twitch",
    offers: [],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}
